const phaseOneCoverageTargets = [
  'src/api/client.ts',
  'src/components/SecureField.tsx',
  'src/context/SessionProvider.tsx',
  'src/features/app-version/AppVersionGate.tsx',
  'src/features/chat/hooks.ts',
  'src/features/notifications/hooks.ts',
  'src/features/notifications/labels.ts',
  'src/features/notifications/sync.ts',
  'src/features/payments/hooks.ts',
  'src/features/ratings/hooks.ts',
  'src/features/ratings/screens/RatingScreen.tsx',
  'src/features/service-requests/hooks.ts',
  'src/features/service-support/hooks.ts',
  'src/features/onboarding/screens/TechnicianProfessionalProfileOnboardingScreen.tsx',
  'src/features/technician/hooks.ts',
  'src/hooks/useSmartPolling.ts',
  'src/navigation/notificationNavigation.ts',
  'src/services/sessionStorage.ts',
  'src/shared/QueryState.tsx',
  'src/shared/apiMessage.ts',
  'src/shared/format.ts',
]

module.exports = {
  preset: 'jest-expo',
  testMatch: ['**/?(*.)+(test).[jt]s?(x)'],
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  clearMocks: true,
  restoreMocks: true,
  collectCoverageFrom: phaseOneCoverageTargets,
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/src/test/',
    '\\.native\\.[jt]sx?$',
    '\\.web\\.[jt]sx?$',
  ],
  coverageReporters: ['text', 'html', 'lcov'],
  coverageThreshold: {
    global: {
      lines: 75,
      functions: 75,
      statements: 75,
      branches: 65,
    },
  },
}
